# Generated by Django 5.1.7 on 2025-03-23 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuarios',
            fields=[
                ('id_prontuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Prontuário')),
                ('credential_id', models.BigIntegerField(unique=True, verbose_name='CNS')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('micro_area', models.IntegerField(verbose_name='Microárea')),
                ('family', models.IntegerField(verbose_name='Família')),
            ],
        ),
    ]
