# Generated by Django 5.1.7 on 2025-03-27 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuarios',
            name='family',
            field=models.IntegerField(verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='prontuarios',
            name='id_prontuario',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Prontuario'),
        ),
        migrations.AlterField(
            model_name='prontuarios',
            name='micro_area',
            field=models.IntegerField(verbose_name='Microarea'),
        ),
        migrations.AlterField(
            model_name='sisuser',
            name='id_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prontuarios.prontuarios', verbose_name='ID Usuario'),
        ),
        migrations.AlterField(
            model_name='sisuser',
            name='user_level',
            field=models.CharField(choices=[('admin_app', 'Administrador do Sistema'), ('admin_staff', 'Administrador Gerencial'), ('admin_same', 'Administrador do Same'), ('user', 'Usuario Comum')], default='user', max_length=50, null=True, verbose_name='Nivel de Acesso'),
        ),
    ]
